---
- hosts: localhost
  connection: local
  roles:
  - role: provision-ec2

- hosts: tag_Name_maze_runner_prod
  become: True
  roles:
#  - role: simple-docker-daemon
  - role: ansible-role-maze-runner